#ifndef DERIVED_CONSTANT_H
#define DERIVED_CONSTANT_H

#include "macro.h"

const Radian EARTH_TILT = DEG_TO_RAD(EARTH_TILT_DEG);
const Radian CYPRUS_LATITUDE = DEG_TO_RAD(CYPRUS_LATITUDE_DEG);

#endif // DERIVED_CONSTANT_H
